<?php require VIEWS . '/includes/header.phtml' ?>

    <div class="row">
        <div class="col-md-12">
            <h1>Usuário</h1>
        </div>
    </div>

    <div class="row">
        <a href="<?=HOME . '?url=users/save';?>" class="btn btn-default">
            Criar Usuário
        </a>
        <hr>
    <div class="row">
        <?php if(isset($_GET['msg']) && $_GET['msg']) : ?>
            <div class="alert alert-success">
                <?= $_GET['msg'];?>
            </div>
        <?php endif; ?>    
    </div>
        
    </div class="row">    
        <table class="table">
            <thead>
                <tr>
                <th>#</th>
                <th>Nome</th>
                <th>Email</th>
                <th>Criado Em</th>
                <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($users as $u):?>
                <tr>
                <td><?=$u['id'];?></td>
                <td><?=$u['name'];?></td>
                <td><?=$u['email'];?></td>
                <td><?=date("d/m/Y H:i:s", strtotime($u['created_at']))?></td>
                <td>
                <a href="<?=HOME?>/?url=users/edit&id=<?=$u['id'];?>" class="btn btn-sm btn-warning">Editar</a>
                    <a href="<?=HOME?>/?url=users/remove&id=<?=$u['id'];?>';" class="btn btn-sm btn-danger">Remover</a>
                </td>
                 </tr>
                 <?php endforeach?>
            </tbody>
        </table>
    </div>
<?php require VIEWS . '/includes/footer.phtml' ?>