<?php require VIEWS . '/includes/header.phtml' ?>

    <div class="row">
        <div class="col-md-12">
            <h1>Usuário</h1>
        </div>
    </div>

    <div class="row">
        <a href="<?=HOME . '?url=users/list';?>" class="btn btn-warning">
            Voltar
        </a>

<form action="<?=HOME . '?url=users/save';?>" method="POST">

  <div class="form-group">
    <label for="exampleInputEmail1">Nome</label>
    <input type="text" class="form-control" placeholder="Nome" name="name">
  </div>

  <div class="form-group">
    <label for="exampleInputEmail1">Email</label>
    <input type="email" class="form-control" placeholder="Email" name="email">
  </div>

  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" placeholder="Password" name="password">
  </div>
  
  <button type="submit" class="btn btn-success">Salvar</button>
</form>
    </div>
<?php require VIEWS . '/includes/footer.phtml' ?>